[package]
name = "dol"
version = "0.1.0"
authors = ["Erin Moon <erin@hashbang.sh>"]
exclude = ["data/*"]

[dependencies]
byteorder = "1.2.3"
itertools = "0.7.8"

[dev-dependencies]
pretty_assertions = "0.5.1"
